#!/bin/sh

set -e

if [ -e /usr/lib/libqsoundcloud.so ]
    then
        rm /usr/lib/libqsoundcloud.so
fi

if [ -e /usr/lib/libqsoundcloud.so.1 ]
    then
        rm /usr/lib/libqsoundcloud.so.1
fi

if [ -e /usr/lib/libqsoundcloud.so.1.0 ]
    then
        rm /usr/lib/libqsoundcloud.so.1.0
fi

if [ -e /usr/lib/libqsoundcloud.so.1.0.0 ]
    then
        rm /usr/lib/libqsoundcloud.so.1.0.0
fi

if [ -h /usr/lib/qt4/imports/QSoundCloud ]
    then
        rm /usr/lib/qt4/imports/QSoundCloud
fi

exit 0
